-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "forecastCoverageDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "forecastSafetyDays" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "leadTimeDays" INTEGER NOT NULL DEFAULT 2;
